CREATE TABLE BOOKS (id INTEGER PRIMARY KEY, name TEXT, rating INTEGER);


INSERT INTO BOOKS VALUES (1, "Метро 2033", 8);
INSERT INTO BOOKS VALUES (2, "Лолита", 7);
INSERT INTO BOOKS VALUES (3, "Аэропорт", 7);
